name: Deploy to Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Install dependencies
      run: |
        npm install

    - name: Build project
      run: |
        npm run build

    - name: Deploy to Lightsail
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@15.188.208.133 << 'EOF'
        cd /path/to/your/frontend
        git pull origin main
        npm install
        npm run build
        sudo cp -r build/* /var/www/html/
        sudo systemctl restart nginx
        EOF
