name: Deploy Frontend

on:
  push:
    branches:
      - main
      - preprod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy
        run: |
          BRANCH_NAME=${{ github.ref_name }}

          if [[ "$BRANCH_NAME" == "main" ]]; then
            API_URL="https://api.hellosoins.com"
          else
            API_URL="https://api.preprod.hellosoins.com"
          fi

          ssh -o StrictHostKeyChecking=no ubuntu@15.188.208.133 << EOF
            set -e

            echo "→ Aller dans le dossier frontend"
            cd ~/apps/hellosoins/frontend/${BRANCH_NAME}

            echo "→ Reset local branch pour éviter les conflits"
            git fetch origin
            git reset --hard origin/${BRANCH_NAME}

            echo "→ Création du fichier .env (non suivi par git)"
            echo "VITE_API_BASE_URL=${API_URL}" > .env

            echo "→ Reconstruction des conteneurs Docker"
            docker-compose down
            docker-compose up -d --build
          EOF
