name: Deploy Frontend

on:
  push:
    branches:
      - main
      - preprod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@15.188.208.133 << EOF
          cd ~/apps/hellosoins/frontend/${{ github.ref_name }}
          git pull origin ${{ github.ref_name }}
          docker-compose down
          docker-compose up -d --build
          EOF
